### ISSUE TITLE
problema con un libro

### ISSUE THREAD

**Issue by comleoita** [Leone25/booktab-downloader#11]
Ciao,
Il tuo script funziona alla grande tranne per un solo libro (L'ora di storia)
quando do invio dopo 10 secondi mi da questo errore:
```
Traceback (most recent call last):
  File "C:\Users\Leonardo Compagnoni\Desktop\booktab-downloader-main\main.py", line 98, in <module>
    key = partXML.getElementsByTagName("content")[0].firstChild.nodeValue
IndexError: list index out of range
```

**Comment by comleoita** [comment]
si ma tranquillo, è di un libro ancora delle media che mi avrebbe fatto piacere averlo in pdf.
se mi dici dove posso trovare lo spine.xml te lo invio

**Comment by comleoita** [comment]
ok

**Comment by Leone25** [comment]
Manda il volume.xml

**Comment by comleoita** [comment]
ecco
[volume.zip](https://github.com/Leone25/booktab-downloader/files/7351043/volume.zip)

**Comment by comleoita** [comment]
se non ti fidi di uno zip (cosa che farei anche io) ti mando il file con l'estensione txt in quanto github non supporta il file xml
 [volume.txt](https://github.com/Leone25/booktab-downloader/files/7351058/volume.txt)

**Comment by comleoita** [comment]
ok ho scoperto questo:
non esiste lo spine.xml di quel libro

**Comment by comleoita** [comment]
ok ti ho scritto su twitter
