### ISSUE TITLE
volume.xml non ha le "entry" da cui prendere il percorso del PDF

### ISSUE THREAD

**Issue by Rarder44** [Leone25/booktab-downloader#13]
quando non viene trovato il file spine.xml viene scaricato il file volume.xml, che ha una sintassi differente.

principalmente andando su 
http://web.booktab.it/boooks_web/CODICE_ISBN/volume.xml
si trovano le "unit"
che riportano a 
http://web.booktab.it/boooks_web/CODICE_ISBN/NOME_UNIT/config.xml

ma in questo file non ci sono le "entry" ( da cui prendere il percorso PDF )
allegato con il file volume e config di un unità
[volume e config.zip](https://github.com/Leone25/booktab-downloader/files/7770095/volume.e.config.zip)

ho provato con vari libri che usano il "volume.xml" e tutti non hanno le entry

**Comment by Leone25** [comment]
Ciao!

Interessante come problema, sembra un'altra versione della struttura del libro . . . però per capire come funziona avrei bisogno di vedere da me. Contattami in privato su twitter (stesso nome + 03) così possiamo parlarne.
