### ISSUE TITLE
Richiesta di aiuto

### ISSUE THREAD

**Issue by gabrySerra** [Leone25/booktab-downloader#15]
Ciao, non riesco a superare il punto 1 e 2.
Entro correttamente con CMD nel percorso dove si trovano il file, ma non riesco ad eseguire il comando "pip install -r requirements.txt" nonostante abbia Python installato (e anche aggiornato).
Grazie in anticipo

**Comment by Leone25** [comment]
Ciao, é un problema comune, che errore ti da?

**Comment by gabrySerra** [comment]
Ciao, grazie della risposta.
Ora ho cambiato computer, e arrivo fino a questo punto:

https://drive.google.com/file/d/1a3sVrxeslxGb0UCWtuPVfRL6Zqqf3UWO/view?usp=sharing

**Comment by Leone25** [comment]
Sembra tutto installato, hai provato adesso a far girare lo script?

**Comment by gabrySerra** [comment]
Sì, ma quando inserisco l'ISBN, improvvisamente Python si chiude

**Comment by gabrySerra** [comment]
Aggiornamento:
ora riesco ad inserire l'ISBN, ma quando inserisco il nome che voglio dare al file, improvvisamente (come prima) Python crasha. Mi sembra molto strano.
Vuoi provare a vedere con TeamViewer?

**Comment by Leone25** [comment]
Contatta mi su Twitter (stesso nome + 03) così ci possiamo accordare

**Comment by gabrySerra** [comment]
Va bene se ci sentiamo su Telegram? E' più veloce per me.
Il mio tag è: @gabrielelcn

**Comment by Leone25** [comment]
Certo
