### ISSUE TITLE
Qualcuno è mai stato bannato?

### ISSUE THREAD

**Issue by Pando13** [Leone25/booktab-downloader#16]
Volevo chiedere se è possibile che si venga bannati se utilizzo questo codice. Vorrei avere i file pdf solo per me per comodità, c'è il rischio ban anche se l'account è utilizzato solo da me?

**Comment by Leone25** [comment]
non ho mai saputo di qualcuno che è stato bannato

il server di per se non si rende consto che non è un browser a richiedere le informazioni quindi a parte per l'uso di banda particolarmente alto non ci sono motivi per cui to dovrebbero bloccare

comunque non ci dovrebbero essere problemi

**Comment by Pando13** [comment]
Grazie mille è andato tutto alla perfezione, l'unico problema è stato trovare l'ISBN giusto.
Consiglio di andare su
`http://web.booktab.it/BooktabWeb/`
selezionare il libro e prelevare dall'URL successivo l'ISBN che si troverà così:
`http://web.booktab.it/BooktabWeb/#/ISBN_GIUSTO/...`

magari in futuro cambieranno il link ma spero di aiutare qualcuno nel caso non accadesse.
