### ISSUE TITLE
Nuovo URL Booktab

### ISSUE THREAD

**Issue by itsmebonny** [Leone25/booktab-downloader#17]
Ciao, ho il sospetto che la struttura dell'url e del token sia cambiata completamente, provando a scaricare un libro continua a darmi errore 301, anche perché non trovo né su firefox né su edge un cookie con _shibsession

**Comment by Leone25** [comment]
probabilmente è il nuovo lettore
come menzionato nel readme, guarda qua https://github.com/Leone25/kitaboo-downloader

**Comment by itsmebonny** [comment]
No, il lettore si trova a https://web-booktab.zanichelli.it, non webreader.zanichelli.it, ma la struttura della pagina sembra completamente diversa. Il libro si trova solo su booktab, ma lo script si rompe perché non esiste più il cookie _shibsession, almeno a un primo sguardo

**Comment by Leone25** [comment]
Ho appena notato, grazie
ho aggiornato il codice e dovrebbe rifunzionare, semplicemente riscarica la repo ed esegui il nuovo codice
