### ISSUE TITLE
Cookies shibsession

### ISSUE THREAD

**Issue by gabboo01** [Leone25/booktab-downloader#18]
Provando a scaricare, e seguendo il procedimento non appare più tra i cookies quello con shibsession, cosa che fino a due settimane fa quando feci l'ultimo download non accadeva. inoltre il libro in questione è visualizabile solo su booktab e non sul nuovo lettore kitaboo

![immagine](https://user-images.githubusercontent.com/93389677/166000512-758e4262-a290-4a49-b4aa-8e2e75820308.png)

**Comment by gabboo01** [comment]
inoltre il libro in questione è visualizabile solo su booktab e non sul nuovo lettore kitaboo

**Comment by Leone25** [comment]
Grazie per la segnalazione, è stato piuttosto facile aggiornare, perfavore riscarica la repo ed esegui il nuovo codice

**Comment by gabboo01** [comment]
Perfetto grazie mille, funzionato però solo con chrome avevo provato prima con firefox e non andava, poi ho notato che il cookie di firefox era diverso da quello di chrome credo quindi che il problemia sia stato li

**Comment by Leone25** [comment]
È un cookie particolarmente lungo, firefox solitamente lo accorcia e mette i ... In mezzo, è piuttosto fastidioso, bisogna selezionare "visualizza header raw" fer sistemare
