### ISSUE TITLE
Aiuto!

### ISSUE THREAD

**Issue by Gaet90P** [Leone25/booktab-downloader#19]
Ciao! Da dove devo aprire la pagina web indicata? Perché con i browser normali non funziona

**Comment by Leone25** [comment]
A quale "pagina indicata" ti riferisci?

**Comment by Gaet90P** [comment]
Questa http://web-booktab.zanichelli.it/

**Comment by Leone25** [comment]
Ti ho già risposto su Twitter ma visto che vedo che non visualizzi il messaggio ti rispondo anche qua

Devi usare il downloader per kitaboo, che il link sul readme
