### ISSUE TITLE
Invalid ISBN, please try again.

### ISSUE THREAD

**Issue by Pando13** [Leone25/booktab-downloader#22]
sto cercando di scaricare i libri dal sito https://web-booktab.zanichelli.it/BooktabWeb/
ho riscontrato problemi nel trovare i cookies, ma nonostante ciò il programma mi da questo errore:
Invalid ISBN, please try again.
l'ISBN credo sia l'unica cosa giusta che ho messo 

https://imgur.com/a/MZuW0iS quale dei due valori devo inserire nel programma?

**Comment by Leone25** [comment]
se è un libro con varie parti devi guardare nell'url e vedere se c'è una parte extra, bisogna inserire anche quella nell'isbn

**Comment by Pando13** [comment]
Risolto grazie mille
