### ISSUE TITLE
Missing PyPDF2 Module

### ISSUE THREAD

**Issue by Simsiano** [Leone25/booktab-downloader#23]
Come avevi scritto dopo aver inserito il comando "pip install requests PyPDF2" dice che l'installazio è completata ma nonostante questo il modulo PyPDF2 non viene caricato.

**Comment by Leone25** [comment]
prova `pip install PyPDF2`

**Comment by Simsiano** [comment]
È la prima cosa che ho provato, infatti la il risultato è Requirement already satisfied.

**Comment by Leone25** [comment]
perfavore esegui `pip -V` e `python -m site` e mostrami il risultato

**Comment by Simsiano** [comment]
Ecco il risultato:


C:\Users\Valerio\Desktop\booktab-downloader-main>py -V
Python 3.10.8

C:\Users\Valerio\Desktop\booktab-downloader-main>python -m site
sys.path = [
    'C:\\Users\\Valerio\\Desktop\\booktab-downloader-main',
    'C:\\Users\\Valerio\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
    'C:\\Users\\Valerio\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
    'C:\\Users\\Valerio\\AppData\\Local\\Programs\\Python\\Python310\\lib',
    'C:\\Users\\Valerio\\AppData\\Local\\Programs\\Python\\Python310',
    'C:\\Users\\Valerio\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages',
]
USER_BASE: 'C:\\Users\\Valerio\\AppData\\Roaming\\Python' (doesn't exist)
USER_SITE: 'C:\\Users\\Valerio\\AppData\\Roaming\\Python\\Python310\\site-packages' (doesn't exist)
ENABLE_USER_SITE: True

**Comment by Leone25** [comment]
il primo comando che hai eseguito non è corretto
`pip -V`, non `py -V`

comunque prova ad installare il modulo con `pip3 install PyPDF2`, magari è quello

**Comment by Simsiano** [comment]
Questo è il risultato ma non credo sia normale:

C:\Users\Valerio\Desktop\Test>py -V
Python 3.10.8

C:\Users\Valerio\Desktop\Test>pip -V
"pip" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

**Comment by Leone25** [comment]
scusa ma se pip no viene riconoscuto come hai fatto ad installare PyPDF2 ?

**Comment by Simsiano** [comment]
Guarda lascia stare ieri pip andava oggi non più, a furia di reinstallare e installare python tutte le funzionalità hanno cominciato a funzionare. Ora però ho un'altro problema, una volta che mi chiede il cookie, che viene riconosciuto, mi chiede l'ISBN che prerò nonostante lo abbia copia-incollato dall'ulr mi segna come invalido. Per caso questo l'ISBN deve essere inserito in questo formato: "xxxxxxxxxxxxx" oppure con i trattini?

**Comment by Leone25** [comment]
coi trattini

**Comment by dtappia** [comment]
ho installato anch'io il tutto ed arrivo fino all'inserimento del cookie e poi ISBN ma non c'è verso di ottenere risposta corretta. Ho sempre ISBN errato inserendo i 13 numeri come da catalogo del libro. Non capisco a quali trattini vi riferite...
Grazie in anticipo per un vostro aiuto

**Comment by Leone25** [comment]
Quando tu apri il libro digitale nel modo ufficiale dal sito web nella barra dell url compare un codice molto simile a quello dell'isbn due volte, ci va quello li quando chiedw l'isbn

**Comment by dtappia** [comment]
> Quando tu apri il libro digitale nel modo ufficiale dal sito web nella barra dell url compare un codice molto simile a quello dell'isbn due volte, ci va quello li quando chiedw l'isbn

grazie per l'info. In effetti ho realizzato che il reader che parte quando seleziono il libro da leggere online è il kitaboo e quindi incompatibile con questo script...il problema è che anche utilizzando il kitaboo link il tentativo di scaricare il pdf va in costante errore di timeout con errore non specifico ad un numero di pagina.

**Comment by Leone25** [comment]
mi stai dicendo che hai provato ad usare il mio script di kitaboo e non va?

**Comment by dtappia** [comment]
> mi stai dicendo che hai provato ad usare il mio script di kitaboo e non va?

chiedo scusa per aver mischiato i due problemi. In effetti ho provato con win10 a scaricare il pdf ma lo script kitaboo, dopo aver acquisito il cookie ed il link per il pdf, inizia a scaricare le pagine ma non è omogeneo nello scarico ed in questo specifico caso mi si blocca in modo random con errore di timeout. il download più lungo è stato di 170 pagine su 500 ma la maggior parte si blocca prima delle 100 pagine. Non capisco se è un problema del server o cos'altro

**Comment by Leone25** [comment]
Ho il sospetto che la tua connessione non sia ottima. . .

**Comment by dtappia** [comment]
> Ho il sospetto che la tua connessione non sia ottima. . .

Devo confermare la tua ipotesi. Stessa macchina messa su una connessione diversa è arrivato fino alla fine senza nessun problema. Mi rimane il dubbio del come mai sulla mia rete che è una fibra ftth vada in timeout....ma questa è un'altra storia.
Ad ogni modo grazie per lo script che ha funzionato perfettamente

**Comment by Leone25** [comment]
credo che il problema sia dovuto alla protezione anti ddos del sito di zanichelli, con la fibra magari è troppo veloce e viene rilevato come attacco ddos e per prevenire danni agli altri utenti vengono bloccate le richieste
