### ISSUE TITLE
Problema con ISBN

### ISSUE THREAD

**Issue by Tricchi** [Leone25/booktab-downloader#25]
Ciao Leone25,
sto provando il tuo script per scaricare pdf da Booktab ma, dopo aver inserito l'ISBN, mi da sempre: "Gethering information about the volume...
Invalid ISBN, please try again.". Il libro non è multivolume ma ho provato a inserire sia l'ISBN nell'URL sia quello sul libro cartaceo. Lo sto provando su un Mac con macOs Big Sur. Da cosa può dipendere?
Grazie.

Marco

**Comment by Leone25** [comment]
perfavore apri https://web-booktab.zanichelli.it/BooktabWeb/ , premi f12 e vai sulla pagina "network", premi sulla copertina del libro da scaricare e adesso guarda nel menu "network" e nella lista cerca la richiesta per lo `spine.xml` oppure `volume.xml` (alcune volte c'è uno o l'altro), clicca sulla richiesta, e nel menù che si apre guarda l'url del file, dovrebbe essere qualcosa del genere `https://web-booktab.zanichelli.it/api/v1/resources_web/*************/spine.xml` , ciò che tu devi inserire come isbn è quel valore che stà al posto delle virgolette.

fammi sapere come va

**Comment by Tricchi** [comment]
Non riesco a trovare ne volume.xml ne spine.xml. Nella colonna "file" ce ne sono altri come user, footer.json ecc.)

**Comment by Leone25** [comment]
mi sa che mi devo collegare io e vedere, perfavore scrivimi in privato su twitter (stesso nome + 03)

**Comment by Leone25** [comment]
fammi uno screenshot della pagina "network" dopo ever seguito le istruzioni che ti ho detto prima fino al passaggio che riesci

**Comment by Tricchi** [comment]
Eccolo.
![Screenshot (8)](https://user-images.githubusercontent.com/10362246/198303042-50b5d455-0e63-478e-85e2-83611e0ff5d0.png)

**Comment by Tricchi** [comment]
Ecco un'altro screenshot dopo aver refreshato la pagina
![Screenshot (9)](https://user-images.githubusercontent.com/10362246/198306934-6e0c8fc2-8b3d-45ad-91f8-348dddf5ef92.png)

**Comment by Leone25** [comment]
che cosa c'è nel `footer.json`?

**Comment by Tricchi** [comment]
Adesso, dopo aver riavviato ho trovato finalmente volume.xml ma dopo aver messo l'ISBN indicato nell'URL mi da sempre lo stesso errore:
![Screenshot (10)](https://user-images.githubusercontent.com/10362246/198324557-4abfaade-e340-4658-a005-35c107641245.png)
![Screenshot (11)](https://user-images.githubusercontent.com/10362246/198324566-d87039bb-0dc5-466b-b62b-06cc6337f9cc.png)

**Comment by Tricchi** [comment]
Nel footer.json c'è questo:
![Screenshot (12)](https://user-images.githubusercontent.com/10362246/198326581-758596a6-c979-4ba7-b395-4f95d0d1c53e.png)

**Comment by Tricchi** [comment]
Però questa schermata è venuta fuori dopo aver fatto un refresh della pagina. Ed è scomparso volume.xml

**Comment by Leone25** [comment]
prova a modificare il lo script a linea 66 dove dice `spine.xml` metti `volume.xml`

**Comment by Tricchi** [comment]
Ho provato ma mi da sempre lo stesso errore. La cosa strana è che quando copio e incollo il cookie se premo subito Invio non succede nulla, mentre se premo alcune volte (a caso) backspace e poi invio appare "Input the ISBN of the book you want to download:". Quindi io inserisco l'ISBN e mi da il solito errore.

**Comment by Tricchi** [comment]
Questo è il testo del cookie: OptanonConsent=isGpcEnabled=0&datestamp=Thu+Oct+27+2022+18%3A56%3A53+GMT%2B0200+(Central+European+Summer+Time)&version=202209.2.0&isIABGlobal=false&hosts=&consentId=6382666e-61d6-48f8-b37b-47923ef736e1&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0003%3A1%2CC0004%3A1%2CC0002%3A1&geolocation=IT%3B62&AwaitingReconsent=false; OptanonAlertBoxClosed=2022-10-24T15:47:49.107Z; _ga_FL8QBN8HHQ=GS1.1.1666889812.8.1.1666889848.0.0.0; _ga=GA1.2.1283185040.1666626469; _fbp=fb.1.1666626469414.2966062…NTAsInVzZXJfaWQiOjEwNTgyMTgsImRlcGFydG1lbnRfaWQiOm51bGwsInJvbGVfaWQiOjQyLCJyb2xlTmFtZSI6Ik1ZWl9VU0VSIn0seyJpZCI6MjA1ODg1MSwidXNlcl9pZCI6MTA1ODIxOCwiZGVwYXJ0bWVudF9pZCI6bnVsbCwicm9sZV9pZCI6MzAsInJvbGVOYW1lIjoiTVlaX1BST0ZFU1NJT05JU1RBIn1dLCJhdHRyaWJ1dGVzIjpbXSwibXl6Ijp7ImlkIjoxNjY0Nzg2LCJncm91cElkIjozMywiaXNDb25maXJtZWQiOnRydWUsImlzQXBwcm92ZWQiOnRydWUsImlzQXV0aG9yaXplZEJ5UGFyZW50Ijp0cnVlfX0.cBBbx30JJ3FB2YmwNRTbb7iILAqqgazul8ej1U-HVTk; booktab_token=ykPA8ch8K1Hg1VRD; _gat_UA-41749706-2=1; _gat_UA-41749706-1=1

**Comment by Tricchi** [comment]
Lo stesso problema me lo da anche con l'altro script che hai fatto su kitaboo. Mentre invece funziona bene quello per Bsmart.

**Comment by Leone25** [comment]
effettivamente sto usando una libreria piuttosto datata per gestire l'input, se vuoi puoi provare a scrivere direttamente il cookie e l'isbn nel codice ma credo di aver capito il problema, perfavore leggi attentamente la nota che sta sotto "how to use" nel `readme`

**Comment by Tricchi** [comment]
Ho provato a mettere il testo del cookie nel file cookies.txt ma purtroppo ancora non funziona.
![Schermata 2022-10-27 alle 22 41 44 PM](https://user-images.githubusercontent.com/10362246/198393771-49719818-f5a8-4aac-9251-f712dc3f8a3a.png)
Da lo stesso errore.

**Comment by Tricchi** [comment]
Ho provato con Chrome e li funziona correttamente!!! Grazie mille!!!

**Comment by Tricchi** [comment]
Ho provato con un secondo libro e mi da questo errore:
![Schermata 2022-10-27 alle 22 58 06 PM](https://user-images.githubusercontent.com/10362246/198396765-59d5decf-9ea8-4705-aecd-b7da6afedf03.png)

**Comment by Leone25** [comment]
Purtroppo quando fa così significa che usa un formato diverso che per adesso non posso convertire :L

**Comment by Tricchi** [comment]
Ok, grazie. Invece ti informo che funziona correttamente anche lo script per kitaboo.
Grazie ancora.
