### ISSUE TITLE
Impossibile trovare i file volume.xml spine.xml

### ISSUE THREAD

**Issue by bludiprussia** [Leone25/booktab-downloader#26]
Ciao Enrico,

ho provato a seguire le tue istruzioni, ma non riesco a trovare i file richiesti dallo script (`spine.xml` e `volume.xml`).

Ho provato sia su Firefox che su Chrome. Aprendo il monitor di rete, gli unici file disponibili sono user.json, footer.json e config.xml (quest'ultimo solo quando carico un capitolo del libro).

Sembra che sia cambiato il modo in cui Booktab recupera i dati dal server. Hai idea se possa esserci una soluzione?

**Comment by Leone25** [comment]
Generalmente capita per due motivi:
1. Stai cercando di scaricare un libro kitaboo  e quindi questo è lo script sbagliato
2. La ci sono dei problemi con la cache del lettore che quindi non fa comparire il file nelle richieste, ci sono un paio di info nella nota

**Comment by bludiprussia** [comment]
Ciao, grazie della risposta.

Posso confermarti che si tratta di un libro booktab.
Quali info intendi? Non ho trovato nulla :/

**Comment by bludiprussia** [comment]
Capisco, però non si tratta di un libro kitaboo. Ci sarebbe modo di risolvere?

**Comment by Leone25** [comment]
Scusa ho letto male, 
Sei sicuro di aver disabilitato le cache?

**Comment by bludiprussia** [comment]
Sì, la cache non è attiva. Allego uno screen illustrativo
![snapshot](https://user-images.githubusercontent.com/106482391/199508689-2a0dcc96-6e45-4898-b45e-579572a55ae0.png)

**Comment by Leone25** [comment]
mi sembra che tu abbia aperto la pagina di rete dopo che tu abbia aperto il libro, ricarica la pagina con la pagina di rete aperta

**Comment by bludiprussia** [comment]
Dopo il refresh non cambia nulla, ottengo solo i due file user.json e footer.json

**Comment by Leone25** [comment]
ok credo che dovrò espolorare più a fond oquesto problema, perfavore scrivimi in privato su twitter (stesso nome + 03)

**Comment by bludiprussia** [comment]
Purtroppo non ho twitter. Va bene se ci sentiamo per email, oppure su telegram?

**Comment by Leone25** [comment]
se mi dici il tuo handle ti posso scrivere su telegram

**Comment by bludiprussia** [comment]
@znoort
