### ISSUE TITLE
Errore cache

### ISSUE THREAD

**Issue by giapponesetimido** [Leone25/booktab-downloader#27]
Buongiorno, dopo aver inserito la cache nel terminale, lo stesso mi restituisce il seguente errore: -bash: syntax error near unexpected token `('

La cache da me inserita è quella presa dal file spine.xml ed è la seguente. Sbaglio qualcosa? Grazie mille

OptanonConsent=isGpcEnabled=0&datestamp=Sun+Nov+06+2022+10%3A06%3A17+GMT%2B0100+(Ora+standard+dell%E2%80%99Europa+centrale)&version=202209.2.0&isIABGlobal=false&hosts=&consentId=76e9dbe9-76e6-40f6-8cf4-bf94ffb9e646&interactionCount=2&landingPath=NotLandingPage&groups=C0001%3A1%2CC0003%3A1%2CC0004%3A1%2CC0002%3A1&AwaitingReconsent=false&geolocation=IT%3B57; myz_session=10124227.636774de242de3.45168004; OptanonAlertBoxClosed=2022-11-06T08:48:31.925Z; stack2=["my.zanichelli.it","web-booktab.zanichelli.it"]; _ga_M3CF5M6GK8=GS1.1.1667724512.1.1.1667724687.0.0.0; _ga=GA1.1.1677904942.1667724512; _ga_FL8QBN8HHQ=GS1.1.1667724512.1.1.1667725577.0.0.0; _gid=GA1.2.958544087.1667724512; _fbp=fb.1.1667724512377.84386952; myz_token=qkpyxbtdvne; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvaWRwLnphbmljaGVsbGkuaXRcL3Y0XC9sb2dpbiIsImlhdCI6MTY2NzcyNDU5NSwiZXhwIjoxNjY4MzI5Mzk1LCJuYmYiOjE2Njc3MjQ1OTUsImp0aSI6IllRbUUyZTdJWkJRMzNsbDIiLCJzdWIiOjkzOTM4MiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImlkIjo5MzkzODIsIm5hbWUiOiJGcmFuY2VzY28gQW5nZWxpbmkiLCJnaXZlbl9uYW1lIjoiRnJhbmNlc2NvIiwiZmFtaWx5X25hbWUiOiJBbmdlbGluaSIsInByZWZlcnJlZF91c2VybmFtZSI6ImNoZWNjb2FuZ2VsaW5pQGdtYWlsLmNvbSIsImVtYWlsIjoiY2hlY2NvYW5nZWxpbmlAZ21haWwuY29tIiwiaXNfdmVyaWZpZWQiOjEsImlzX2VtcGxveWVlIjowLCJpc19teXphbmljaGVsbGkiOjEsImNyZWF0ZWRfYXQiOiIyMDIyLTEwLTA0IDA3OjI3OjE0IiwidXBkYXRlZF9hdCI6bnVsbCwibGFzdF9hY3Rpdml0eV9hdCI6IjIwMjItMTEtMDYgMDg6MDI6NDAiLCJyb2xlcyI6W3siaWQiOjE4MjU1ODIsInVzZXJfaWQiOjkzOTM4MiwiZGVwYXJ0bWVudF9pZCI6bnVsbCwicm9sZV9pZCI6NDIsInJvbGVOYW1lIjoiTVlaX1VTRVIifSx7ImlkIjoxODI1NTgzLCJ1c2VyX2lkIjo5MzkzODIsImRlcGFydG1lbnRfaWQiOm51bGwsInJvbGVfaWQiOjMwLCJyb2xlTmFtZSI6Ik1ZWl9QUk9GRVNTSU9OSVNUQSJ9XSwiYXR0cmlidXRlcyI6W10sIm15eiI6eyJpZCI6MjU1NzQ1MiwiZ3JvdXBJZCI6MzMsImlzQ29uZmlybWVkIjp0cnVlLCJpc0FwcHJvdmVkIjp0cnVlLCJpc0F1dGhvcml6ZWRCeVBhcmVudCI6dHJ1ZX19.jV1qS9rwNl-3XwbC1o_Gb2Dt5jBu6E3w7oroY0UTsK8; booktab_token=YQmE2e7IZBQ33ll2; _gat_UA-41749706-1=1

**Comment by Leone25** [comment]
you have some weird cookie values, i'd suggest you clear all the page cookies and then try again
