### ISSUE TITLE
"Pip" non è riconosciuto come comando

### ISSUE THREAD

**Issue by lucabordignonb** [Leone25/booktab-downloader#29]
Ricevo l'errore "pip" non è riconosciuto come comando pur localizzando il terminale nella cartella dove ho scaricato tutti i file. Come è possibile? 

Grazie mille

**Comment by Leone25** [comment]
https://duckduckgo.com/?q=pip+not+recognized&ia=web

**Comment by lucabordignonb** [comment]
> https://duckduckgo.com/?q=pip+not+recognized&ia=web

Risolto, grazie mille e complimenti ancora per il lavoro fatto
