### ISSUE TITLE
Il terminale python crasha dopo che inserisco l'ISBN 

### ISSUE THREAD

**Issue by ThunderAlex17** [Leone25/booktab-downloader#31]
Ciao, dopo aver fatto tutta la procedura correttamente, inserito il valore del cookie, inserisco l'ISBN, e il terminale di python crasha senza permettermi di inserire il nome del pdf, e di conseguenza senza permettermi di creare il file.

**Comment by Leone25** [comment]
prova ad aseguirlo manualmente e vedere che errore ti da

per far ciò vai nella cartella dove si trova lo script, con niente selezionato premi shift + tasto destro del mouse e seleziona "apri finestra powershell qui" e poi esegui lo script scrivendo "python main.py" ed esegui la procedura come al solito, poi quando ti compare un errore manda qua.

**Comment by ThunderAlex17** [comment]
![Immagine 2022-12-28 173525](https://user-images.githubusercontent.com/121528252/209843688-911f1026-cdac-4c12-9022-f776bd5fc673.png)

**Comment by Leone25** [comment]
Allora prova ad eseguirlo con "python3 main.py"

Se continua a non andare cerca su google "come aggiungere python a path" e riprova i due comandi prima, uno dei due deve andare

**Comment by ThunderAlex17** [comment]
stesso problema. ho python istallato su path e continua a darmi quest'errore con entrambi i comandi. Ho riprovato ad aprire il file python e nulla, continua ad andare in crash quando inserisco l'ISBN

**Comment by Leone25** [comment]
perfavore contattami in privato su twitter (stesso nome + 03) così posso darti meglio una mano
