### ISSUE TITLE
Not able to get the pdf

### ISSUE THREAD

**Issue by sasxzece** [Leone25/booktab-downloader#32]
Hi, I tried using this program and it all worked, except for the fact that after putting the pdf name, it doesn't pop up in the program folder. How can I solve? Thanks :)

**Comment by Leone25** [comment]
did you get any errors?
did you use a simple file name?

**Comment by sasxzece** [comment]
No, the program just close and when I check in my desktop folder I don't find anything (name used: "prova"). Do I have to install some pdf module? Thanks 🙏

**Comment by Leone25** [comment]
al posto di avviare il programma facendo doppio click, prova a fare cosi: apri la cartella dove si trova lo script, senza selezionare nessun file fai shift + tasto destro in un area senza file e seleziona "apri terminale qua" (o qualcosa del genere) e poi nel terminale scrivi `python main.py` (alcune volte è `python3 main.py`) e poi fai tutto come al solito, a sto giro dovrebbe rimanere il terminale aperto e mostrarti l'errore

**Comment by sasxzece** [comment]
Grazie mille, adesso trovo il PDF! Veramente gentile e disponibile
