### ISSUE TITLE
PyPDF2.errors.PdfReadError: PDF starts with '{"err', but '%PDF-' expected

### ISSUE THREAD

**Issue by sasxzece** [Leone25/booktab-downloader#33]
Ciao, scusa ancora per il disturbo ma questo è ciò che compare ad un mio amico. E' possibile risolvere?

**Comment by Leone25** [comment]
stessa risposta che ho dato anche ad un altro, mi servirebbe vedere i file che vengono scaricati, ma questo richiede un po' di esperienza ed è comunque non la migliore idea discuterne pubblicamente, se vuoi puoi scrivermi in privato su twitter (stesso nome + 03)

**Comment by sasxzece** [comment]
Ok, richiesta appena mandata

**Comment by Leone25** [comment]
non ho ancora ricevuto niente, sei sicuro di aver scritto alla persona giusta? dovrebbe esserci lo stesso logo

**Comment by sasxzece** [comment]
Mi chiamo MarcoSi59178628 
Quando scrivo un messaggio viene fuori invio annullato.
