### ISSUE TITLE
ERRORI

### ISSUE THREAD

**Issue by notcarmx** [Leone25/booktab-downloader#34]
![image](https://user-images.githubusercontent.com/129877480/229838121-45d34383-b506-4bf5-914b-4401e1b04027.png)
Dopo vari problemi (mi crashava, ho dovuto usare chrome anzichè firefox, "invalid ISBN") sono riuscito a risolvere ma ora ci sono altri problemi che non riesco a  capire

**Comment by notcarmx** [comment]
token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvaWRwLnphbmljaGVsbGkuaXRcL3Y0XC9sb2dpbiIsImlhdCI6MTY4MDYyMDUwMCwiZXhwIjoxNjgxMjI1MzAwLCJuYmYiOjE2ODA2MjA1MDAsImp0aSI6IjBpTDhxY1JUbjQzUENieVciLCJzdWIiOjkzMzYyNiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImlkIjo5MzM2MjYsIm5hbWUiOiJDYXJtaW5lIFBldHJvenppZWxsbyIsImdpdmVuX25hbWUiOiJDYXJtaW5lIiwiZmFtaWx5X25hbWUiOiJQZXRyb3p6aWVsbG8iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJjYXJtaW5lcDIwMDdAZ21haWwuY29tIiwiZW1haWwiOiJjYXJtaW5lcDIwMDdAZ21haWwuY29tIiwiaXNfdmVyaWZpZWQiOjEsImlzX2VtcGxveWVlIjowLCJpc19teXphbmljaGVsbGkiOjEsImNyZWF0ZWRfYXQiOiIyMDIyLTEwLTAzIDEzOjIwOjM5IiwidXBkYXRlZF9hdCI6IjIwMjMtMDEtMTkgMjE6NTc6NTMiLCJsYXN0X2FjdGl2aXR5X2F0IjoiMjAyMy0wNC0wNCAxNDozODoxMCIsInJvbGVzIjpbeyJpZCI6MTgxNDIwMywidXNlcl9pZCI6OTMzNjI2LCJkZXBhcnRtZW50X2lkIjpudWxsLCJyb2xlX2lkIjo0Miwicm9sZU5hbWUiOiJNWVpfVVNFUiJ9LHsiaWQiOjE4MTQyMDQsInVzZXJfaWQiOjkzMzYyNiwiZGVwYXJ0bWVudF9pZCI6bnVsbCwicm9sZV9pZCI6MjMsInJvbGVOYW1lIjoiTVlaX1NUVURFTlRFIn1dLCJhdHRyaWJ1dGVzIjpbXSwibXl6Ijp7ImlkIjoyODU3MDQzLCJpc0NvbmZpcm1lZCI6dHJ1ZSwiaXNBcHByb3ZlZCI6dHJ1ZSwiaXNBdXRob3JpemVkQnlQYXJlbnQiOnRydWUsImdyb3VwSWQiOjE0fX0.9kk62LCvZgV3K5SUEQ9z2r5YouloqFI6F-rv_C2gvkk; booktab_token=0iL8qcRTn43PCbyW

Questo è il cookie inserito

**Comment by piumalinux** [comment]
Funziona anche con https://web-booktab.zanichelli.it? e con https://my.zanichelli.it/dashboard/home? Mi continua a dire "invalid ISBN"

**Comment by Leone25** [comment]
Questo particolare script funziona con i libri presenti su https://web-booktab.zanichelli.it/
Per i libri che hanno il simbolo "la Z" guarda lo script kitaboo linkato sul readme

**Comment by piumalinux** [comment]
Grazie!
