### ISSUE TITLE
volume.xml and spine.xml don't exists

### ISSUE THREAD

**Issue by jacula** [Leone25/booktab-downloader#36]
Hello,

I tried it, but your sentence:

"_Back in the network tools look for the volume.xml or spine.xml file that should appear in the network tab_"

is not right (I think :-)). The files volume.xml and spine.xml don't exists.

**Comment by Leone25** [comment]
Does your book open in web-booktab.zanichelli.it or webreader.zanichelli.it?

**Comment by Mario03482** [comment]
I have the same problem. It opens in webreader.zanichelli.it

**Comment by Leone25** [comment]
Then you need to use the kitaboo downloader, it's linked at the top of the readme

**Comment by jacula** [comment]
Yes, you are right 😉
