### ISSUE TITLE
EOF marker not found

### ISSUE THREAD

**Issue by BlackDragonMT99** [Leone25/booktab-downloader#38]
Hi, I tried your program today for the first time following the instructions but I keep receiving this error:

PyPDF2.errors.PdfReadError: EOF marker not found

It would be great if there was a solution thanks.

**Comment by Leone25** [comment]
No idea never had this issue

**Comment by BlackDragonMT99** [comment]
If it helps, it appeared after changing the PdfFileReader() function with the PdfReader() function in order to solve the previous error that apeared:

pypdf2.errors.pdfreaderror: pdf starts with '{"err', but '%pdf-' expected

The same happens if I keep using the PdfFileReader() function with the addition of the "strict" attribute:

PdfFileReader("example.pdf", strict=False)

I can solve the    '{"err', but '%pdf-' expected    error but not the   EOF marker not found    error.

**Comment by Leone25** [comment]
hmmmm,
i think that there is some kind of error in the request and the server is responding with some json, that's why it's crashing
