### ISSUE TITLE
Blank PDF

### ISSUE THREAD

**Issue by serleenax** [Leone25/booktab-downloader#39]
![image](https://github.com/Leone25/booktab-downloader/assets/144935096/0b18ce23-4142-4d78-92ce-44bc8ec06d67)
This is the error, pdf completly empty when trying to download a Zanichelli book

**Comment by serleenax** [comment]
Per specificare, pagine giuste numero perfetto, ma sono completamente vuote e il file è di quale kb per un libro da 700+ pagine

**Comment by Leone25** [comment]
Buon giorno, ho ricevuto vari messaggi da molteplici persone che hanno riscontrato questo problema, ciò è dovuto ad un recente aggiornamento del sito che cripta tutte le pagine dei libri. Ho dato un rapido sguardo ed attualmente non mi sembra troppo chiaro come il tutto funzioni quindi un aggiornamento richiederà del tempo. Sono comunque aperto a contributi da parte di terzi.
