### ISSUE TITLE
booktab app vs sito web

### ISSUE THREAD

**Issue by LEO-CAF** [Leone25/booktab-downloader#41]
io ho attivato i libri sul sito di zanichelli, poi li ho ritrovati tutti sull'applicazione di booktab per telefono e per computer invece sul sito web di booktab ce ne sono solo 1/3 di quelli che ho attivato, perché? c'è un modo per sincronizzarli così li posso attivare? per risolvere questo problema avevo pensato di scaricare i libri con la repository di kitaboo (che se ho capito bene utilizza il sito zanichelli) ma ho problemi a farla funzionare, grazie in anticipo

p.s. se hai tempo puoi aggiornare la repository di pearson

![Screenshot 2023-09-22 alle 18 33 51](https://github.com/Leone25/booktab-downloader/assets/100777689/362bc178-31cb-4a1f-b0d2-bba0ce841759)
![Screenshot 2023-09-22 alle 18 33 47](https://github.com/Leone25/booktab-downloader/assets/100777689/911c2dd2-3c4c-4f37-ace0-18729d2a71d1)

**Comment by Leone25** [comment]
Quelli che non vedi sul sito di booktab è perché si vedono con un altro webreader, se vai su my.zanichelli.it te li mostra e c'è un link per vederli, il reader si chiama kitaboo e puoi trovare il programma per scaricare all'inizio del readme
