### ISSUE TITLE
No run python program on macos 

### ISSUE THREAD

**Issue by fedeTrade** [Leone25/booktab-downloader#43]
ciao, non riesco ad eseguire main.py su macOS. Ho seguito tutti i comandi precedenti e controllato la versione di Python, ma quando inserisco il comando `python3 main.py` non esegue niente.

**Comment by Leone25** [comment]
Mai visto una roba del genere, mi spiace ma non so come aiutarti

**Comment by ImmortalChanger** [comment]
Qual è l'output?
