### ISSUE TITLE
Codice ISBN invalido

### ISSUE THREAD

**Issue by ImmortalChanger** [Leone25/booktab-downloader#44]
Sto provando a scaricare un libro (ISBN: 9788808432155) ma lo script mi dice 

**"Invalid ISBN, please try again."** 

pur sapendo benissimo che l'ISBN è corretto perché l'ho copiato e incollato. Ho verificato almeno 4 volte i cookies e l'ISBN del libro. [Qui](https://streamable.com/b1xj5m) una dimostrazione. Ho anche provato a cambiare il codice dello script per cercare direttamente il libro senza farsi dare l'ISBN dall'utente (link diretto al file *spine.xml*) ma nulla ha funzionato. In passato funzionava, adesso non più, apparentemente. Forse è un'errore nel codice perché ho già dovuto aggiustare il percorso in cui lo script cercava il file *cookies.txt* perché non lo trovava, ma onestamente mi sembra tutto apposto.

Sto usando macOS 10.15.7 con Python 3.12 e 3.11 ma nessuno dei due funziona.

**Comment by ErricoV1** [comment]
Il codice non funziona più, prova PDFGrabber di FelixFrog
