### ISSUE TITLE
codice token non valido young hub

### ISSUE THREAD

**Issue by ddev1n** [Leone25/booktab-downloader#45]
Ciao ho provato il tuo script ma non funziona quando inserisco il token come viene spiegato nella guida. @Leone25  . devinbeqja90@gmail.com per contattamri anche perche' non so bene come funziona github

**Comment by Leone25** [comment]
"non funziona" è un po' troppo generico, potresti perfavore mostrare l'errore che ti compare?

**Comment by ddev1n** [comment]
Obtaining volume info . . .
undefined:1
Not Found
^

SyntaxError: Unexpected token 'N', "Not Found" is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///C:/Users/xxxx/Downloads/hub-young-downloader-main/hub-young-downloader-main/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/xxxx/Downloads/hub-young-downloader-main/hub-young-downloader-main/index.js:65:22
    Questo succede ogni volta che provo a mettere il token nel terminale. Ho provato anche con mettendo i raw headers ma non funziona.

**Comment by Leone25** [comment]
ok ho appena notato che chiedi di hub young, non capisco perchè hai aperto la issue qua, ma va be...

in ogni caso, stavo riprovando anch'io lo script e sto notanto che non funziona più neanche a me, ma per motivi diversi e temo che si siano accorti che avevano lasciato abilitato una cosa assai importante che permette di scaricare i pdf in originale, e quindi adesso l'hanno disabilitato...

comunque possiamo provare a vedere cosa non va a te

puoi provare ad inserire tra riga 64 e 65 `console.log(code)`, per iniziare a vedere cosa non va...

**Comment by ddev1n** [comment]
Ho riprovato ad inserire `console.log(code)` e sta volta mi ha scaricato il pdf, il problema e' che mi da un errore nell'aprirlo .
![Screenshot 2024-04-01 183220](https://github.com/Leone25/booktab-downloader/assets/136709575/bcf705ad-0a15-4e21-a649-845ae973fc47)

**Comment by Leone25** [comment]
apri il pdf generato con notepad, probabilmente ci sarà scritto "forbitten", che è il mio stesso errore di quella cosa che ti dicevo

onestamente non ho molta voglia di sistemarlo, anche perchè ho poco interesse dato che nnon mi serve più questo script... vedrò se per caso trovo qualcosa...

**Comment by ddev1n** [comment]
sisi, mi da lo stesso errore.

**Comment by Leone25** [comment]
questo problema è stato risolto nella nuova versione dello script grazie l'aiuto di un contributore
