### ISSUE TITLE
crasha

### ISSUE THREAD

**Issue by sefirothmorpheus** [Leone25/booktab-downloader#46]
![booktab1](https://github.com/Leone25/booktab-downloader/assets/156643499/e50ba57d-c024-49b9-87ea-ccf5187c4468)
![booktab2](https://github.com/Leone25/booktab-downloader/assets/156643499/c9182349-8603-43ae-a648-2d37c67def3b)

**Comment by Leone25** [comment]
hm, questo sembra più un problema coi pdf della zanichelli che con lo script...

ciò che si potrebbe fare (come ho già fatto con un altro script) è aggiungere l'opzione di scaricare i pdf singoli e poi usare pdftk per unirli, attualmente però non ho tempo di farlo, se però te hai voglia di fare questa piccola modifica, sei benvenuto...
