### ISSUE TITLE
titolo senza volume.xml or spine.xml

### ISSUE THREAD

**Issue by sefirothmorpheus** [Leone25/booktab-downloader#47]
ciao
volevo segnalare che su alcuni titoli non ci sono volume.xml o spine.xml

![image](https://github.com/user-attachments/assets/a77e66df-6bec-4526-b934-9d3f4e39285f)

come si vede nell'immagine, l'unico xml si chiama ping

copiando il suo cookie, il tool non scarica nessun libro dando come errore: "invalid ISBN, please try again"

da qunato vedo dai miei libri, quelli che non hanno volume.xml o spine.xml presentano nella loro immagine della copertina una nuvolettta rossa in basso a sinistra

![image](https://github.com/user-attachments/assets/7480dccf-3fc4-423d-b6c2-1c8dc8de9c76)

**Comment by Leone25** [comment]
sei sicuro che sia un libro booktab e non kitabook?

**Comment by sefirothmorpheus** [comment]
me li apre su booktab quando clicco da myzanichelli...

**Comment by Leone25** [comment]
hm, curioso...

messaggiami in privato su twitter (stesso nome + 03), magari riesco a risolvere

**Comment by sefirothmorpheus** [comment]
![image](https://github.com/user-attachments/assets/d959e7e4-90d5-4651-ab37-eee397fff94e)

![booktab3](https://github.com/user-attachments/assets/37973031-2606-456b-ad74-a9e3f0abfc3c)

la cosa interessante è che il tool di kitabook vede come isbn 9788808062079 mentre su booktab mi da 9788808238016

ti ho scritto anche su twitter
