### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by aleeessio** [Leone25/booktab-downloader#5]
Sorry bro..but I've a problem. When I run the script I get this error: ModuleNotFoundError: No module named 'requests'

**Comment by Leone25** [comment]
you may have got the modules not propperly installed . . . .

try again installing modules manually with `python -m pip install requests`

**Comment by aleeessio** [comment]
> you may have got the modules not propperly installed . . . .
> 
> try again installing modules manually with `python -m pip install requests`

Thanks, it worked! 
Fra sei na bestia fattelo di..da mesi cercavo un modo per booktab..grazie davvero!

**Comment by Leone25** [comment]
Di niente, odio anch'io i lettori che ti danno
