### ISSUE TITLE
Wrong ISBN even if it is correct 

### ISSUE THREAD

**Issue by mattiacolombomc** [Leone25/booktab-downloader#7]
I've tried to download the book **that I already bought** with this ISBN: 9788808235510 

I know you use the ISBN to generate the download link via RegEx, but I don't know why your tool doesn't seem to work with the following link, so I thought it could've been useful to let you know.

http://web.booktab.it/BooktabWeb/#/9788808235510/9788808235510/

_Note: the tool works fine for me with every other book_

**Comment by Leone25** [comment]
This is a very weird issue, if you'd like further help please dm me on my twitter with the same username + 03 so that i can redirect you to a more private chartroom

**Comment by mattiacolombomc** [comment]
Sent!
Il 27 set 2021, 11:37 +0200, Enrico ***@***.***>, ha scritto:
