### ISSUE TITLE
Unable to download book, Invalid ISBN error

### ISSUE THREAD

**Issue by Ciancy28** [Leone25/booktab-downloader#8]
I'm trying to download "Matematica.verde 4A - Seconda edizione" and "Matematica.verde 4B - Seconda edizione" both bundled with ISBN: 9788808439291
All i get is "Invalid ISBN, please try again."

**Comment by Leone25** [comment]
Hmm interesting issue . . . 

If you try to open the book with the web viewer how does it appear? Is it 2 separate books or just one?

If it's 2 separate take a look at thibsn that appears for the 2 different books and try to input those where it asks about the isbn

**Comment by Ciancy28** [comment]
> If you try to open the book with the web viewer how does it appear? Is it 2 separate books or just one?
> 
3 separate books
![Immagine 2021-10-03 131058](https://user-images.githubusercontent.com/77066322/135751052-4412bd42-c08a-4502-b999-987d4b02682b.png)

> If it's 2 separate take a look at thibsn that appears for the 2 different books and try to input those where it asks about the isbn

That's what i wanted to try as well but i can't find the ISBN for the single books

**Comment by Leone25** [comment]
usually it's in the address bar, it should look something like this `http://web.booktab.it/BooktabWeb/#/*************/*************` where the `*` are the actual isbn (it's repeated 2 times)

**Comment by Ciancy28** [comment]
> usually it's in the address bar, it should look something like this `http://web.booktab.it/BooktabWeb/#/*************/*************` where the `*` are the actual isbn (it's repeated 2 times)

That seems to have worked!  
The codes were 9788808312037-1 and 9788808312037-2

**Comment by Leone25** [comment]
cool!
