### ISSUE TITLE
Books not downloading if they do not appear on BookTab

### ISSUE THREAD

**Issue by Francesco-Avagliano** [Leone25/booktab-downloader#9]
Basically, Zanichelli let you see only a selection of your activated books on their website, and for seeing all of them you have to download their software.

In fact, at first I activated the book on my main account and I while I was seeing it on the software I couldn't see it on their web platform.

Thinking it was a problem on my end, I borrowed an account from a friend of a mine and I activated his book on his account, but as you can see on the video I'm uploading, the only way would be to open settings and opening the book from there and not on book tab web.

Here's the video where I've explained the problem, it would be great if you implement a way to extract the pdf even from the settings (as I've explained in the video). Thank you!

https://youtu.be/K5pxqn-roog

**Comment by Leone25** [comment]
The book you are showing gets opened with the kitaboo web reader, please use the alternative script mentioned in the readme.md to download it
